#url = https://www.saucedemo.com/
#url = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
url = https://www.sisense.com/
#browser =LAMBDACHROME: To test on LambdaTest with Google Chrome
#browser =LAMBDAFIREFOX:To test on LambdaTest with Mozilla Firefox
#browser =LAMBDAEDGE :To test on LambdaTest with Microsoft Edge
#browser =BROWSERCHROME : To test on BrowserStack with Google Chrome
#browser =BROWSERFIREFOX : To test on BrowserStack with Mozilla Firefox
#browser =BROWSEREDGE : To test on BrowserStack with Microsoft Edge

browser=firefox,headless
version=148
platform=Windows 10
retryFailedTestCases=no

!!!!Enabled your api url!!!!

!!!!UiRL for REST API!!!!
#baseURL = https://petstore.swagger.io/v2

!!!URL for SOAP API!!!!
#baseURL=http://www.dneonline.com

!!!!URL for GraphQL API!!!!
#baseURL=https://hasura.io
bearerToken=Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik9FWTJSVGM1UlVOR05qSXhSRUV5TURJNFFUWXdNekZETWtReU1EQXdSVUV4UVVRM05EazFNQSJ9.eyJodHRwczovL2hhc3VyYS5pby9qd3QvY2xhaW1zIjp7IngtaGFzdXJhLWRlZmF1bHQtcm9sZSI6InVzZXIiLCJ4LWhhc3VyYS1hbGxvd2VkLXJvbGVzIjpbInVzZXIiXSwieC1oYXN1cmEtdXNlci1pZCI6ImF1dGgwfDY1ZTA4MDI5NWFhZTA3NTQxMDJjZDNiYSJ9LCJuaWNrbmFtZSI6ImFudXNoYS5sIiwibmFtZSI6ImFudXNoYS5sQGtpd2lxYS5jb20iLCJwaWN0dXJlIjoiaHR0cHM6Ly9zLmdyYXZhdGFyLmNvbS9hdmF0YXIvNjcyMDhjOWFmNTU4Y2U4NDk1N2M3ZmYyNWFjN2U3ZDI_cz00ODAmcj1wZyZkPWh0dHBzJTNBJTJGJTJGY2RuLmF1dGgwLmNvbSUyRmF2YXRhcnMlMkZhbi5wbmciLCJ1cGRhdGVkX2F0IjoiMjAyNC0wNS0xM1QxMjozNzowNC4xNDhaIiwiaXNzIjoiaHR0cHM6Ly9ncmFwaHFsLXR1dG9yaWFscy5hdXRoMC5jb20vIiwiYXVkIjoiUDM4cW5GbzFsRkFRSnJ6a3VuLS13RXpxbGpWTkdjV1ciLCJpYXQiOjE3MTU2NjU2MzAsImV4cCI6MTcxNTcwMTYzMCwic3ViIjoiYXV0aDB8NjVlMDgwMjk1YWFlMDc1NDEwMmNkM2JhIiwiYXRfaGFzaCI6IjFrSEZJMVBuVFE4Mms1Q05RdlBFX3ciLCJzaWQiOiJHc1dCdzh6azd4cENVNGhZTnJjZ25VWVd6Y0o5NkdIbiIsIm5vbmNlIjoieExENU1PZ190VFZ3ejBJODNWd2dqUFpuemRaS2I5Q1AifQ.hEUeK5ZR2y_BUh8bZ_j3AOCcmF1FDLD11RRpwvGkJwDq0tvmEUMFPW-EMhAe6itGcVT2baOOzT78mQraqajydNUOymNVGje6UPzHNliiMqs9K9LVwse4nFVChEIqtao8Nga36dsKr99l0GucmNQLHkSwllS3LfVhg4094j9IlA4dicsbo_eA0HcOpJ6xkVk4LSyOBPRia3q3p68Vl-eU9xt4ZA1q5j27vzHUKTHejnB6fFrcdfqIoePSF60K3uG2voqN1ZtLpuT1xU65Bh3Mqzi0P9knuEgcAO1du3i7jpWVHmbrOqQUi0gwE-EaqZgbgP0qraI59Scz-cjh7Hrj1Q

#lambda-username=kiwiqalambdatest
#lambda-access-key=vO6IeJNebgyeJVzKnEFeatmw8AZxHX5aKpOGO7hjOnGOn207w4

browserstack_username=meethyadav_caCEO0
browserstack_accessKey=ETVPjqbwS1GauU4YWHPf